export const sampleExerciseEntries = {
	1: {
		setterId: 9,
		setter: "jimbob",
		goalId: 21,
		exerciseEntryId: 1,
		exerciseEntry: {
			exercises:[
				{
					name: "Pushups",
					sets: 3,
					reps: 20,
					time: 5,
					entryId: 1,
					userId: 9,
				},
				{
					name: "Situps",
					sets: 4,
					reps: 50,
					time: 10,
					entryId: 1,
					userId: 9,
				},
				{
					name: "Crunches",
					sets: 10,
					reps: 10,
					time: 2,
					entryId: 1,
					userId: 9,
				},
				{
					name: "Leg lifts",
					sets: 3,
					reps: 15,
					time: 3,
					entryId: 1,
					userId: 9,
				},
				{
					name: "Toe touches",
					sets: 2,
					reps: 30,
					time: 2,
					entryId: 1,
					userId: 9,
				},
			],
			date: "2023-04-15",
			note: "I can't touch my toes and it makes me sad",
			rating: 5
		}
	},
	2: {
		setterId: 9,
		setter: "jimbob",
		goalId: 21,
		exerciseEntryId: 2,
		exerciseEntry: {
			exercises:[
				{
					name: "Swim",
					sets: 3,
					reps: 100,
					time: 20,
					entryId: 2,
					userId: 9,
				},
				{
					name: "Plank",
					sets: 4,
					reps: 100,
					time: 2,
					entryId: 2,
					userId: 9,
				},
				{
					name: "Yoga",
					sets: 1,
					reps: 1,
					time: 30,
					entryId: 2,
					userId: 9,
				},
				{
					name: "Pilates",
					sets: 2,
					reps: 1,
					time: 30,
					entryId: 2,
					userId: 9,
				},
			],
			date: "2023-04-20",
			note: "Stamina was low but managed to complete all exercises, need to improve form on plank",
			rating: 3
		}
	},
	3: {
		setterId: 9,
		setter: "jimbob",
		goalId: 21,
		exerciseEntryId: 3,
		exerciseEntry: {
			exercises:[
				{
					name: "Muscle-ups",
					sets: 3,
					reps: 0,
					time: 10,
					entryId: 3,
					userId: 9,
				},
				{
					name: "Burpees",
					sets: 4,
					reps: 10,
					time: 2,
					entryId: 3,
					userId: 9,
				},
				{
					name: "Pullups",
					sets: 5,
					reps: 10,
					time: 3,
					entryId: 3,
					userId: 9,
				},
				{
					name: "Chinups",
					sets: 5,
					reps: 8,
					time: 3,
					entryId: 3,
					userId: 9,
				},
			],
			date: "2023-04-10",
			note: "Why did I think I was ready to do muscle ups",
			rating: 2,
		},
	},
	44: {
		setterId: 9,
		setter: "jimbob",
		goalId: 21,
		exerciseEntryId: 44,
		exerciseEntry: {
			exercises:[
				{
					name: "Goal kicks",
					sets: 5,
					reps: 50,
					time: 45,
					entryId: 44,
					userId: 9,
				},
				{
					name: "Jumping jacks",
					sets: 4,
					reps: 25,
					time: 10,
					entryId: 44,
					userId: 9,
				},
				{
					name: "Agility drills",
					sets: 2,
					reps: 30,
					time: 10,
					entryId: 44,
					userId: 9,
				},
				{
					name: "Kettlebell raises",
					sets: 4,
					reps: 10,
					time: 8,
					entryId: 44,
					userId: 9,
				},
				{
					name: "Squats",
					sets: 3,
					reps: 5,
					time: 5,
					entryId: 44,
					userId: 9,
				},
				{
					name: "Leg raises",
					sets: 3,
					reps: 15,
					time: 5,
					entryId: 44,
					userId: 9,
				},
				{
					name: "Shoulder shrugs",
					sets: 3,
					reps: 15,
					time: 5,
					entryId: 44,
					userId: 9,
				},
			],
			date: "2023-04-08",
			note: "I can't feel anything anymore",
			rating: 4,
		},
	},
	62: {
		setterId: 9,
		setter: "jimbob",
		goalId: 21,
		exerciseEntryId: 62,
		exerciseEntry: {
			exercises:[
				{
					name: "Eat pizza",
					sets: 5,
					reps: 4,
					time: 15,
					entryId: 62,
					userId: 9,
				},
				{
					name: "Pound shots",
					sets: 20,
					reps: 2,
					time: 5,
					entryId: 62,
					userId: 9,
				},
				{
					name: "Kegstand",
					sets: 1,
					reps: 1,
					time: 1,
					entryId: 62,
					userId: 9,
				},
				{
					name: "Beer pong",
					sets: 3,
					reps: 1,
					time: 1,
					entryId: 62,
					userId: 9,
				},
				{
					name: "Bar hop",
					sets: 12,
					reps: 2,
					time: 90,
					entryId: 62,
					userId: 9,
				},
			],
			date: "2023-04-08",
			note: "Best exercise evar",
			rating: 5,
		},
	},
};